# e도커 컴포즈 버전
version: '3.8'

services:
  mysql:
    container_name: batch_mysql_local
    image: mysql
    # 생명주기 유지하기 위한 속성
    volumes:
      # 특정 속성을 초기화 시켜줄 때 도와줌 ex) mysql collation 초기설정
      - ./db/conf.d:/etc/mysql/conf.d
      # 처음 데이터베이스 셋팅을 도와줌
      - ./db/initdb.d:/docker-entrypoint-initdb.d

    ports:
      - "3306:3306"

    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
#    command: --default-authentication-plugin=mysql_native_password
#    restart: always
    environment:
      - MYSQL_DATABASE=pass_local
      - MYSQL_USER=pass_local_user
      - MYSQL_PASSWORD=passlocal123
      - MYSQL_ROOT_PASSWORD=passlocal123
      - TZ=Asia/Seoul

