# mysql? ??????? inmemory DB? ???? ???? ???? ? ??.
#spring:
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: pass_local
#    password: passlocal123
#    driver-class-name: org.h2.Driver

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pass_local?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: pass_local_user
    password: passlocal123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari: # Spring Boot2?? default DBCP? hikariCP???.
      maximum-pool-size: 20             # pool? ?? ??? ?? connection ?
      # minimum-idle: 20                  maximum-pool-size? ????? ??? ?????.

  batch:
    job:
      enabled: false # ??? true? Spring Boot ?? ? ???? ?? Job?? ?????.
    jdbc:
      # Batch? ???? SQL ??? ????? ?????. ????? ???? ????? ?????, always ??? ?? ???? ???? ?? ????? ? ????.
      # ?? ??? ???? ???? ???.
      initialize-schema: always


